image: "nisectuni/qubip-ossl-rust-runner:latest-nix"
variables:
  GIT_SUBMODULE_STRATEGY: recursive

default:
  before_script:
    - export DEBIAN_FRONTEND=noninteractive

    # Spit out relevant info
    - rustc --version
    - cargo --version
    - openssl version -a

stages:
  - lint
  - test

just-list:
  stage: test
  script:
    - cargo build
    - openssl list -verbose -providers -provider $PWD/target/debug/libaurora.so
    - openssl list -verbose -all-algorithms -provider $PWD/target/debug/libaurora.so

test-code:
  stage: test
  script:
    - cargo test --no-fail-fast
    #- cargo install cargo-tarpaulin
    #- cargo tarpaulin --ignore-tests

test-doc:
  stage: test
  script:
    - cargo doc --document-private-items

lint-code:
  stage: lint
  script:
    #- rustup component add rustfmt
    - cargo fmt -- --check
    #- rustup component add clippy
    #- cargo clippy -- -D warnings
# audit-code:
#   stage: test
#   script:
#     - cargo install cargo-audit
#     - cargo audit
