[package]
name = "aurora"
version = "0.8.0-dev"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "aurora"

[features]
# default = ["env_logger", "export"]
default = ["env_logger"]
env_logger = ["dep:env_logger"]
export = []

[dependencies]
function_name = "0.3"
libc = "0.2"
log = "0.4"
openssl_provider_forge = { version = "=0.8.2-dev", git = "https://github.com/qubip/openssl-provider-forge-rs", tag = "nt/v0.8.2-alpha2" }
env_logger = { version = "0.11.7", optional = true }
libcrux-kem = "0.0.2-alpha.3"
rand = "0.8"
anyhow = "1.0"
kem = "0.3.0-pre.0"
rand_core = "0.6.4"
pqcrypto-mldsa = "0.1.0"
pqcrypto-traits = "0.3.5"
asn1 = "0.21.0"
zeroize = "1.8.1"
