[package]
name = "aurora"
version.workspace = true
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "aurora"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["pretty_env_logger"]
pretty_env_logger = ["dep:pretty_env_logger"]

[dependencies]
function_name = "0.3.0"
libc = "0.2.152"
log = "0.4.20"
num-traits = "0.2.19"
pretty_env_logger = { version = "0.5.0", optional = true }

[build-dependencies]
bindgen = "0.69"
