[package]
name = "aurora"
version = "0.7.2-dev"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "aurora"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["pretty_env_logger"]
pretty_env_logger = ["dep:pretty_env_logger"]

[dependencies]
function_name = "0.3"
libc = "0.2"
log = "0.4"
openssl_provider_forge = { version = "=0.8.0", git = "https://github.com/qubip/openssl-provider-forge-rs", tag = "v0.8.0" }
pretty_env_logger = { version = "0.5", optional = true }
libcrux-kem = "0.0.2-alpha.3"
rand = "0.8"
anyhow = "1.0"
kem = "0.3.0-pre.0"
rand_core = "0.6.4"
