[package]
name = "aurora"
version.workspace = true
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "aurora"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["pretty_env_logger"]
pretty_env_logger = ["dep:pretty_env_logger"]

[dependencies]
function_name = "0.3"
libc = "0.2"
log = "0.4"
rust-openssl-core-provider = { path = "../rust-openssl-core-provider" }
pretty_env_logger = { version = "0.5", optional = true }
libcrux-kem = "0.0.2-alpha.3"
rand = "0.8.5"
anyhow = "1.0.94"
