---
name: Rust tests

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
  pull_request_target:
jobs:
  lint-code:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: read
    container: "nisectuni/qubip-ossl-rust-runner:latest-nix"
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v1
      - name: "Check rustc version"
        run: rustc --version
      - name: "Check cargo version"
        run: cargo --version
      - name: "Check openssl version"
        run: openssl version -a
      - run: cargo fmt -- --check
  test-code:
    runs-on: ubuntu-latest
    container: "nisectuni/qubip-ossl-rust-runner:latest-nix"
    permissions:
      contents: read
      statuses: read
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v1
      - name: "Check rustc version"
        run: rustc --version
      - name: "Check cargo version"
        run: cargo --version
      - name: "Check openssl version"
        run: openssl version -a
      - name: "Execute cargo test"
        run: cargo test
  test-code-pqclean:
    runs-on: ubuntu-latest
    container: "nisectuni/qubip-ossl-rust-runner:latest-nix"
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
      statuses: read
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v1
      - name: "Check rustc version"
        run: rustc --version
      - name: "Check cargo version"
        run: cargo --version
      - name: "Check openssl version"
        run: openssl version -a
      - name: "Install jaq to query Cargo.toml"
        run: CARGO_INSTALL_ROOT=/ cargo install jaq
      - name: "Execute cargo test selecting pqclean"
        run: |
          QUERY='.features.default - ["default_adapters"] + .features.default_adapters - ["mldsa_native_adapter"] + ["pqclean_adapter"] | join(",")'
          TEST_FEATURES="$(jaq -r "$QUERY" Cargo.toml)"
          # We must set TEST_NO_DEFAULT_FEATURES and TEST_FEATURES as inherited
          # environment variables when running `cargo test`.
          # Without this, the cdylib may be built with a different feature set than
          # the one used for the tests themselves.
          #
          # Integration tests (the ones in `/tests/`) use a custom setup that invokes
          # `cargo build` at the beginning of their execution to ensure the aurora
          # cdylib is up-to-date.
          #
          # However, Cargo does not propagate the CLI flags of `cargo test` (such as
          # `--no-default-features` and `--features=...`) to subprocesses.
          # As a result, when the test binaries run and their `setup()` executes,
          # this feature configuration is no longer visible.
          # Consequently, the `cargo build` invoked from within the integration tests
          # would run with default features enabled unless we explicitly forward the
          # desired configuration via environment variables.
          #
          # These environment variables MUST be kept in sync with the `cargo test`
          # CLI arguments.
          # Since Cargo does not propagate feature flags to subprocesses, this manual
          # forwarding is required to ensure the inner `cargo build` uses the same
          # feature configuration.
          TEST_NO_DEFAULT_FEATURES=1 TEST_FEATURES="$TEST_FEATURES" cargo test --no-fail-fast --no-default-features --features="${TEST_FEATURES}"
  just-list:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: read
    container: "nisectuni/qubip-ossl-rust-runner:latest-nix"
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v1
      - name: "Check rustc version"
        run: rustc --version
      - name: "Check cargo version"
        run: cargo --version
      - name: "Check openssl version"
        run: openssl version -a
      - name: "Build"
        run: cargo build
      - run: openssl list -verbose -providers -provider $PWD/target/debug/libaurora.so
      - run: openssl list -verbose -all-algorithms -provider $PWD/target/debug/libaurora.so
  build-doc:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: read
    container: "nisectuni/qubip-ossl-rust-runner:latest-nix"
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v1
      - name: "Check rustc version"
        run: rustc --version
      - name: "Check cargo version"
        run: cargo --version
      - name: "Check openssl version"
        run: openssl version -a
      - run: cargo doc --document-private-items
